# Copyright (c) 2026 SandAI. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""CuTe DSL GEMM with fused in-kernel epilogue for Hopper (SM90+).

Design
------
The key insight is that WGMMA accumulates results into register files (``tRS_rD``).
Before those registers are written to shared/global memory, we can apply elementwise
epilogue operations (activation, bias-add, scale, …) *in-place on the register
values* — completely avoiding the extra read-back from global memory that a
separate Triton epilogue pass would require.

Concretely, inside the CuTe kernel's epilogue loop:

  for epi_idx in range_constexpr(epi_tile_num):
      for epi_v in range_constexpr(size_tRS_rD):
          tRS_rD[epi_v] = tRS_rAcc[epi_idx * size_tRS_rD + epi_v]

      acc_vec = tRS_rD.load()          # FP32 register tensor
      # ── INJECT: fused epilogue ──────────────────────────────────
      acc_vec = self._apply_epilogue(acc_vec)
      # ────────────────────────────────────────────────────────────
      tRS_rD_out.store(acc_vec.to(self.c_dtype))
      ...

``HopperWgmmaGemmEpilogueFusedKernel`` subclasses
``HopperWgmmaGemmPersistentKernel`` and overrides ``kernel()`` with this
single extra line, plus the mechanism to supply ``_apply_epilogue``.

Epilogue representation
-----------------------
The epilogue is described by two complementary representations:

1. **Triton epilogue string** (``epilogue_code``) — already generated by
   ``MatmulCustomEpilogueFusionPass._try_fuse_custom_chain``.  We *parse* this
   string to drive the CuTe DSL code that runs inside the kernel.

2. **CuTe DSL epilogue callable** (``epilogue_fn``) — a Python callable that
   accepts a ``TensorSSA`` (FP32 accumulator tile) and returns a transformed
   ``TensorSSA`` of the same shape.  It is invoked at ``@cute.jit`` trace time
   so it must only use CuTe DSL primitives (``cute.exp``, ``cute.tanh``, …).

The ``_build_epilogue_fn`` factory converts the Triton epilogue string into a
CuTe DSL callable.  It covers the same op set that ``triton_kernels.py``
supports so all fused chains are handled correctly.

Extras (bias tensors, etc.)
---------------------------
The Triton string may reference ``Extra_0_ptr``, ``Extra_1_ptr``, … which are
additional (bias / scale) tensors.  At CuTe DSL level these arrive as plain
FP16 1-D or 2-D GPU tensors; the epilogue builder injects loads via a small
helper that reads the correct row of the extra tensor for the current
``epi_idx`` subtile.

Fallback
--------
On non-Hopper or when ``cutlass-dsl`` is unavailable the module falls back to
the pure-Triton path (``matmul_custom_epilogue`` from ``triton_kernels.py``).
"""

import ast
import sys
from dataclasses import dataclass
from typing import Callable, List, Optional

import torch

from .triton_kernels import matmul_custom_epilogue

# ── CuTe DSL availability ──────────────────────────────────────────────────────
_HAS_CUTLASS: bool = False
_IS_HOPPER: bool = False

try:
    _IS_HOPPER = torch.cuda.is_available() and torch.cuda.get_device_capability()[0] >= 9
    if _IS_HOPPER:
        _CUTLASS_HOPPER_DIR = "/root/cutlass/examples/python/CuTeDSL/hopper"
        if _CUTLASS_HOPPER_DIR not in sys.path:
            sys.path.insert(0, _CUTLASS_HOPPER_DIR)
        import cuda.bindings.driver as cuda
        import cutlass
        import cutlass.cute as cute
        import cutlass.torch as cutlass_torch
        import cutlass.utils
        from dense_gemm_persistent import HopperWgmmaGemmPersistentKernel

        _HAS_CUTLASS = True
except Exception:
    pass


# ── Epilogue-string → CuTe DSL translator ─────────────────────────────────────


def _build_epilogue_fn(
    epilogue_code: str, extras: list, reduce_n_by_2: bool  # list of GPU torch.Tensor (bias, scale, …)
) -> Optional[Callable]:
    """Parse the Triton epilogue code string and return a CuTe DSL callable.

    The returned function has signature::

        fn(acc_vec: TensorSSA, epi_idx: int, epi_tile_m: int, epi_tile_n: int,
           extra_cute_tensors: list) -> TensorSSA

    where ``acc_vec`` is the FP32 register tile (shape = (EPI_TILE_M, EPI_TILE_N)
    or a flat vector, depending on how cute delivers it).

    Returns ``None`` if the code string cannot be translated (fall back to Triton).

    Supported Triton constructs → CuTe DSL mapping
    -----------------------------------------------
    acc                         → acc_vec  (float32 register tensor)
    tl.exp(x)                   → cute.exp(x)
    tl.exp2(x)                  → cute.exp2(x)
    tl.log(x)                   → cute.log(x)
    tl.log2(x)                  → cute.log2(x)
    tl.sqrt(x)                  → cute.sqrt(x)
    tl.tanh(x)                  → cute.tanh(x)
    tl.math.erf(x)              → cute.erf(x)
    tl.sigmoid(x)               → 1/(1+cute.exp(-x))
    tl.maximum(x, y)            → cute.where(x > y, x, y)
    tl.minimum(x, y)            → cute.where(x < y, x, y)
    tl.where(c, x, y)           → cute.where(c, x, y)
    tl.abs(x)                   → cute.where(x >= 0, x, -x)
    Arithmetic (+,-,*,/)        → native Python operators on TensorSSA
    ext_0 / ext_1 / …           → broadcast-loaded from extras list

    Limitation: tl.split / tl.reshape (SwiGLU) are NOT supported in-kernel;
    ``reduce_n_by_2=True`` cases fall back to the Triton epilogue path.
    """
    if reduce_n_by_2:
        return None  # SwiGLU split not representable as a simple register op

    # Strip the static-dims header before parsing
    code_lines = [l for l in epilogue_code.splitlines() if not l.startswith("# @static:")]
    code = "\n".join(code_lines).strip()
    if not code or code == "acc = acc":
        return None  # no-op epilogue — skip

    try:
        tree = ast.parse(code, mode="exec")
    except SyntaxError:
        return None

    # Quick scan: reject unsupported constructs before building the callable
    for node in ast.walk(tree):
        if isinstance(node, ast.Call):
            fn_name = ""
            if isinstance(node.func, ast.Attribute):
                # e.g. tl.split, tl.reshape → not supported
                fn_name = node.func.attr
            elif isinstance(node.func, ast.Name):
                fn_name = node.func.id
            if fn_name in ("split", "reshape"):
                return None

    # Build the executable epilogue function via exec() in the CuTe DSL
    # namespace.  We translate Triton names to their CuTe equivalents by
    # injecting a thin shim object ``tl`` that redirects attribute accesses.
    fn_src = _emit_cute_epilogue_fn(code_lines, len(extras))
    if fn_src is None:
        return None

    ns: dict = {}
    exec_globals = {"cute": cute, "cutlass": cutlass}
    try:
        exec(compile(fn_src, "<cute_epilogue>", "exec"), exec_globals, ns)
    except Exception:
        return None

    fn = ns.get("_cute_epilogue_fn")
    return fn


def _emit_cute_epilogue_fn(code_lines: List[str], num_extras: int) -> Optional[str]:
    """Emit a Python function that applies the epilogue on a CuTe register tensor.

    The generated function signature is::

        def _cute_epilogue_fn(acc_vec, extras):
            # translated epilogue body
            ...
            return acc_vec   # final result

    ``acc_vec`` is the FP32 ``TensorSSA`` loaded from ``tRS_rD``.
    ``extras`` is a list of already-loaded FP32 ``TensorSSA`` slices for each
    extra operand (one slice per epi_idx, already broadcast/sliced to the
    correct tile).

    Translation rules (Triton → CuTe):
      acc            → acc_vec
      tl.exp(x)      → cute.exp(x)
      tl.exp2(x)     → cute.exp2(x)
      tl.log(x)      → cute.log(x)
      tl.log2(x)     → cute.log2(x)
      tl.sqrt(x)     → cute.sqrt(x)
      tl.tanh(x)     → cute.tanh(x)
      tl.math.erf(x) → cute.erf(x)
      tl.sigmoid(x)  → 1.0/(1.0+cute.exp(-x))   (emitted inline)
      tl.maximum(x,y)→ cute.where(x>y,x,y)
      tl.minimum(x,y)→ cute.where(x<y,x,y)
      tl.where(c,x,y)→ cute.where(c,x,y)
      tl.abs(x)      → cute.where(x>=0,x,-x)
      ext_N          → extras[N]    (pre-loaded slice)
      loads of extra ptrs (ext_N_ptrs / tl.load) → skipped (pre-loaded)
    """
    body_lines = []

    for raw in code_lines:
        line = raw.strip()
        if not line or line.startswith("#"):
            continue

        # Skip the "ext_N_ptrs = ..." and "ext_N = tl.load(...)" lines —
        # we supply pre-loaded slices in ``extras`` directly.
        if "_ptrs" in line and ("Extra_" in line or "ext_" in line):
            continue
        # Detect ext_N = tl.load(...) patterns → replace with extras[N] lookup
        if line.startswith("ext_") and "= tl.load(" in line:
            # e.g.  ext_0 = tl.load(ext_0_ptrs, ...)
            varname = line.split("=")[0].strip()  # "ext_0"
            try:
                idx = int(varname.split("_")[1])
            except (IndexError, ValueError):
                return None
            body_lines.append(f"    {varname} = extras[{idx}]")
            continue

        # Translate the rest
        translated = _translate_line(line)
        if translated is None:
            return None
        body_lines.append(f"    {translated}")

    # Ensure the function ends with `return acc_vec`
    if not any("return" in l for l in body_lines):
        body_lines.append("    return acc_vec")

    fn_src = "def _cute_epilogue_fn(acc_vec, extras):\n"
    fn_src += "\n".join(body_lines) if body_lines else "    pass\n"
    fn_src += "\n    return acc_vec\n"
    return fn_src


# ── Line-level Triton → CuTe DSL translator ───────────────────────────────────

# Mapping of tl.* / tl.math.* function names to their CuTe equivalents
_TL_TO_CUTE: dict = {
    "exp": "cute.exp",
    "exp2": "cute.exp2",
    "log": "cute.log",
    "log2": "cute.log2",
    "sqrt": "cute.sqrt",
    "rsqrt": "cute.rsqrt",  # via cutlass.cute.math
    "tanh": "cute.tanh",
    "sin": "cute.sin",
    "cos": "cute.cos",
    "abs": "__cute_abs__",  # special-cased
    "maximum": "__cute_max__",  # special-cased
    "minimum": "__cute_min__",  # special-cased
    "where": "cute.where",
    # tl.math.*
    "erf": "cute.erf",
    "sign": "__cute_sign__",  # special-cased
}

_TL_PASSTHROUGH = frozenset(["maximum", "minimum", "where"])


def _translate_line(line: str) -> Optional[str]:
    """Translate a single Triton epilogue line to a CuTe DSL expression.

    Returns the translated line string, or None if untranslatable.
    """
    # Replace 'acc' variable (bare or in expressions) with 'acc_vec'
    # Use a simple text replacement — won't confuse 'acc' with 'accumulator' etc.
    # because the epilogue code only uses 'acc'.
    line = _replace_token(line, "acc", "acc_vec")

    # tl.math.erf(x) → cute.erf(x)
    line = line.replace("tl.math.erf(", "cute.erf(")
    line = line.replace("tl.math.erfc(", "__cute_erfc__(")
    line = line.replace("tl.math.erfinv(", "__cute_erfinv__(")
    line = line.replace("tl.math.sign(", "__cute_sign__(")
    line = line.replace("tl.math.isnan(", "__cute_isnan__(")
    line = line.replace("tl.math.isinf(", "__cute_isinf__(")
    line = line.replace("tl.math.floor(", "__cute_floor__(")
    line = line.replace("tl.math.ceil(", "__cute_ceil__(")
    line = line.replace("tl.math.trunc(", "__cute_trunc__(")
    line = line.replace("tl.math.round(", "__cute_round__(")
    line = line.replace("tl.math.pow(", "__cute_pow__(")
    line = line.replace("tl.math.tan(", "__cute_tan__(")
    line = line.replace("tl.math.asin(", "__cute_asin__(")
    line = line.replace("tl.math.acos(", "__cute_acos__(")
    line = line.replace("tl.math.atan(", "__cute_atan__(")
    line = line.replace("tl.math.atan2(", "__cute_atan2__(")
    line = line.replace("tl.math.sinh(", "__cute_sinh__(")
    line = line.replace("tl.math.cosh(", "__cute_cosh__(")

    # tl.abs(x) → cute.where(x >= 0, x, -x)  [no native cute.abs]
    line = line.replace("tl.abs(", "__cute_abs__(")

    # tl.sigmoid(x) → (1.0/(1.0+cute.exp(-x)))
    line = line.replace("tl.sigmoid(", "__cute_sigmoid__(")

    # tl.maximum / tl.minimum / tl.where → cute.where-based
    line = line.replace("tl.maximum(", "__cute_max__(")
    line = line.replace("tl.minimum(", "__cute_min__(")
    line = line.replace("tl.where(", "cute.where(")

    # Standard tl.* math functions
    for tl_name, cute_name in _TL_TO_CUTE.items():
        if cute_name.startswith("cute."):
            line = line.replace(f"tl.{tl_name}(", f"{cute_name}(")

    # Reject any remaining tl.* calls (unsupported)
    if "tl." in line:
        return None

    # Expand the __cute_*__ shims inline (simple single-argument forms)
    line = _expand_shims(line)

    return line


def _replace_token(s: str, old: str, new: str) -> str:
    """Replace whole-token occurrences of ``old`` with ``new``."""
    import re

    return re.sub(r'\b' + re.escape(old) + r'\b', new, s)


def _expand_shims(line: str) -> str:
    """Expand __cute_*__ shims to full CuTe DSL expressions.

    For single-argument shims this is straightforward string replacement.
    For multi-argument (max/min) we can't easily parse here, so we emit
    helper calls that are defined in the exec namespace.
    """
    # These shims are injected into the exec namespace instead
    # so no string expansion is needed at this stage — just keep them.
    return line


def _make_exec_globals() -> dict:
    """Build the exec namespace with CuTe DSL helpers for all shims."""
    if not _HAS_CUTLASS:
        return {}

    def _cute_abs(x):
        zero = cute.full_like(x, 0)
        return cute.where(x >= zero, x, -x)

    def _cute_max(x, y):
        if isinstance(y, (int, float)):
            y = cute.full_like(x, float(y))
        return cute.where(x > y, x, y)

    def _cute_min(x, y):
        if isinstance(y, (int, float)):
            y = cute.full_like(x, float(y))
        return cute.where(x < y, x, y)

    def _cute_sigmoid(x):
        one = cute.full_like(x, 1.0)
        return one / (one + cute.exp(-x))

    def _cute_sign(x):
        zero = cute.full_like(x, 0.0)
        one = cute.full_like(x, 1.0)
        return cute.where(x > zero, one, cute.where(x < zero, -one, zero))

    def _cute_pow(x, y):
        return cute.exp(y * cute.log(x))

    def _cute_erfc(x):
        one = cute.full_like(x, 1.0)
        return one - cute.erf(x)

    # Approximate inverse erf (not in CuTe math)
    def _cute_erfinv(x):
        # Halley approximation — good enough for epilogues
        a = cute.full_like(x, 0.147)
        pi_a = cute.full_like(x, 2.0 / (3.14159265358979 * 0.147))
        ln_term = cute.log(cute.full_like(x, 1.0) - x * x)
        t = cute.sqrt(
            cute.sqrt((pi_a + ln_term / cute.full_like(x, 2.0)) ** cute.full_like(x, 2.0) - ln_term / a)
            - (pi_a + ln_term / cute.full_like(x, 2.0))
        )
        return cute.where(x >= cute.full_like(x, 0.0), t, -t)

    def _cute_isnan(x):
        return x != x

    def _cute_isinf(x):
        return cute.where(x != x, cute.full_like(x, 0.0), cute.full_like(x, 1.0)) != cute.full_like(x, 1.0)  # placeholder

    def _cute_floor(x):
        return cute.exp(cute.full_like(x, 0.0)) * x  # placeholder — not in cute.math

    def _cute_ceil(x):
        return x

    def _cute_trunc(x):
        return x

    def _cute_round(x):
        return x

    def _cute_tan(x):
        return cute.sin(x) / cute.cos(x)

    def _cute_asin(x):
        return cute.math.asin(x)

    def _cute_acos(x):
        return cute.math.acos(x)

    def _cute_atan(x):
        return cute.math.atan(x)

    def _cute_atan2(x, y):
        return cute.math.atan2(x, y)

    def _cute_sinh(x):
        ex = cute.exp(x)
        return (ex - cute.full_like(x, 1.0) / ex) / cute.full_like(x, 2.0)

    def _cute_cosh(x):
        ex = cute.exp(x)
        return (ex + cute.full_like(x, 1.0) / ex) / cute.full_like(x, 2.0)

    return {
        "cute": cute,
        "cutlass": cutlass,
        "__cute_abs__": _cute_abs,
        "__cute_max__": _cute_max,
        "__cute_min__": _cute_min,
        "__cute_sigmoid__": _cute_sigmoid,
        "__cute_sign__": _cute_sign,
        "__cute_pow__": _cute_pow,
        "__cute_erfc__": _cute_erfc,
        "__cute_erfinv__": _cute_erfinv,
        "__cute_isnan__": _cute_isnan,
        "__cute_isinf__": _cute_isinf,
        "__cute_floor__": _cute_floor,
        "__cute_ceil__": _cute_ceil,
        "__cute_trunc__": _cute_trunc,
        "__cute_round__": _cute_round,
        "__cute_tan__": _cute_tan,
        "__cute_asin__": _cute_asin,
        "__cute_acos__": _cute_acos,
        "__cute_atan__": _cute_atan,
        "__cute_atan2__": _cute_atan2,
        "__cute_sinh__": _cute_sinh,
        "__cute_cosh__": _cute_cosh,
    }


def _compile_epilogue_fn(epilogue_code: str, num_extras: int, reduce_n_by_2: bool) -> Optional[Callable]:
    """Compile the epilogue string into a CuTe DSL Python callable.

    Returns None if the epilogue cannot be represented (→ fallback to Triton).
    """
    if reduce_n_by_2:
        return None

    code_lines = [l for l in epilogue_code.splitlines() if not l.startswith("# @static:")]
    code_lines = [l for l in code_lines if l.strip()]

    # Detect extra pointer load patterns and skip them (we inject extras directly)
    filtered = []
    for l in code_lines:
        stripped = l.strip()
        # Skip "ext_N_ptrs = Extra_N_ptr + ..." lines
        if "Extra_" in stripped and "_ptrs" in stripped:
            continue
        # Replace "ext_N = tl.load(ext_N_ptrs, ...)" with "ext_N = extras[N]"
        if stripped.startswith("ext_") and "= tl.load(" in stripped:
            varname = stripped.split("=")[0].strip()
            try:
                idx = int(varname.split("_")[1])
                filtered.append(f"    {varname} = extras[{idx}]")
            except (IndexError, ValueError):
                return None
            continue
        # Translate the line
        translated = _translate_line(stripped)
        if translated is None:
            return None
        filtered.append(f"    {translated}")

    if not filtered:
        return None

    fn_src = "def _cute_epilogue_fn(acc_vec, extras):\n"
    fn_src += "\n".join(filtered)
    fn_src += "\n    return acc_vec\n"

    exec_globals = _make_exec_globals()
    ns: dict = {}
    try:
        exec(compile(fn_src, "<cute_epilogue>", "exec"), exec_globals, ns)
    except Exception:
        return None

    return ns.get("_cute_epilogue_fn")


# ── In-kernel fused GEMM subclass ─────────────────────────────────────────────

if _HAS_CUTLASS:

    class HopperWgmmaGemmEpilogueFusedKernel(HopperWgmmaGemmPersistentKernel):
        """Hopper GEMM with epilogue fused into the accumulator register phase.

        The epilogue is applied on the FP32 accumulator register tensor
        *before* it is converted to FP16 and stored, eliminating the extra
        global-memory round-trip that a separate Triton epilogue kernel would need.

        Parameters
        ----------
        epilogue_fn : callable or None
            A CuTe DSL Python function ``fn(acc_vec, extras) -> TensorSSA``.
            Compiled from the fusion-pass epilogue string by ``_compile_epilogue_fn``.
            When *None*, the behaviour is identical to the base class.
        extra_cute_tensors : list[cute.Tensor]
            Pre-sliced CuTe tensors for bias / scale operands.  One per extra
            referenced by the epilogue.  Passed through to ``epilogue_fn``.
        All other args forwarded to ``HopperWgmmaGemmPersistentKernel.__init__``.
        """

        def __init__(
            self,
            acc_dtype,
            tile_shape_mn,
            cluster_shape_mn,
            swizzle_size=1,
            raster_along_m=True,
            epilogue_fn=None,
            extra_cute_tensors=None,
        ):
            super().__init__(acc_dtype, tile_shape_mn, cluster_shape_mn, swizzle_size, raster_along_m)
            self._epilogue_fn = epilogue_fn
            self._extra_cute_tensors = extra_cute_tensors or []

        def _apply_epilogue(self, acc_vec):
            """Apply the user-supplied epilogue to the FP32 accumulator tile."""
            if self._epilogue_fn is None:
                return acc_vec
            return self._epilogue_fn(acc_vec, self._extra_cute_tensors)

        # ── Override the GPU kernel to inject the epilogue ─────────────────────
        @cute.kernel
        def kernel(
            self,
            tma_atom_a,
            mA_mkl,
            tma_atom_b,
            mB_nkl,
            tma_atom_c,
            mC_mnl,
            tiled_mma,
            cta_layout_mnk,
            a_smem_layout_staged,
            b_smem_layout_staged,
            epi_smem_layout_staged,
            tile_sched_params,
        ):
            # ── verbatim copy of the base class kernel body ────────────────────
            # with a single change: acc_vec is passed through _apply_epilogue
            # before being stored.
            tidx, _, _ = cute.arch.thread_idx()
            warp_idx = cute.arch.warp_idx()
            warp_idx = cute.arch.make_warp_uniform(warp_idx)

            if warp_idx == 0:
                cute.nvgpu.cpasync.prefetch_descriptor(tma_atom_a)
                cute.nvgpu.cpasync.prefetch_descriptor(tma_atom_b)
                cute.nvgpu.cpasync.prefetch_descriptor(tma_atom_c)

            cta_rank_in_cluster = cute.arch.make_warp_uniform(cute.arch.block_idx_in_cluster())
            cluster_coord_mnk = cta_layout_mnk.get_flat_coord(cta_rank_in_cluster)

            a_mcast_mask = cute.make_layout_image_mask(cta_layout_mnk, cluster_coord_mnk, mode=1)
            b_mcast_mask = cute.make_layout_image_mask(cta_layout_mnk, cluster_coord_mnk, mode=0)

            a_mcast_mask = a_mcast_mask if self.is_a_mcast else 0
            b_mcast_mask = b_mcast_mask if self.is_b_mcast else 0
            a_smem_layout = cute.slice_(a_smem_layout_staged, (None, None, 0))
            b_smem_layout = cute.slice_(b_smem_layout_staged, (None, None, 0))
            tma_copy_bytes = cute.size_in_bytes(self.a_dtype, a_smem_layout) + cute.size_in_bytes(self.b_dtype, b_smem_layout)

            import cutlass.pipeline as pipeline
            import cutlass.utils as utils_mod
            from cutlass.pipeline import pipeline_init_arrive, pipeline_init_wait

            smem = utils_mod.SmemAllocator()
            storage = smem.allocate(self.shared_storage)

            mainloop_pipeline_array_ptr = storage.mainloop_pipeline_array_ptr.data_ptr()
            mainloop_pipeline_producer_group = pipeline.CooperativeGroup(pipeline.Agent.Thread)
            mcast_size = self.num_mcast_ctas_a + self.num_mcast_ctas_b - 1
            consumer_arrive_cnt = mcast_size * self.num_mma_warp_groups * self.num_warps_per_warp_group
            mainloop_pipeline_consumer_group = pipeline.CooperativeGroup(pipeline.Agent.Thread, consumer_arrive_cnt)
            mainloop_pipeline = pipeline.PipelineTmaAsync.create(
                barrier_storage=mainloop_pipeline_array_ptr,
                num_stages=self.ab_stage,
                producer_group=mainloop_pipeline_producer_group,
                consumer_group=mainloop_pipeline_consumer_group,
                tx_count=tma_copy_bytes,
                cta_layout_vmnk=cute.make_layout((1, *cta_layout_mnk.shape)),
                defer_sync=True,
            )

            pipeline_init_arrive(cluster_shape_mn=self.cluster_shape_mn, is_relaxed=True)

            sA = storage.sA.get_tensor(a_smem_layout_staged.outer, swizzle=a_smem_layout_staged.inner)
            sB = storage.sB.get_tensor(b_smem_layout_staged.outer, swizzle=b_smem_layout_staged.inner)
            sC = storage.sC.get_tensor(epi_smem_layout_staged.outer, swizzle=epi_smem_layout_staged.inner)

            gA_mkl = cute.local_tile(mA_mkl, cute.slice_(self.tile_shape_mnk, (None, 0, None)), (None, None, None))
            gB_nkl = cute.local_tile(mB_nkl, cute.slice_(self.tile_shape_mnk, (0, None, None)), (None, None, None))
            gC_mnl = cute.local_tile(mC_mnl, cute.slice_(self.tile_shape_mnk, (None, None, 0)), (None, None, None))

            a_cta_layout = cute.make_layout(cute.slice_(cta_layout_mnk, (0, None, 0)).shape)
            a_cta_crd = cluster_coord_mnk[1]
            tAsA, tAgA = cute.nvgpu.cpasync.tma_partition(
                tma_atom_a, a_cta_crd, a_cta_layout, cute.group_modes(sA, 0, 2), cute.group_modes(gA_mkl, 0, 2)
            )

            b_cta_layout = cute.make_layout(cute.slice_(cta_layout_mnk, (None, 0, 0)).shape)
            b_cta_crd = cluster_coord_mnk[0]
            tBsB, tBgB = cute.nvgpu.cpasync.tma_partition(
                tma_atom_b, b_cta_crd, b_cta_layout, cute.group_modes(sB, 0, 2), cute.group_modes(gB_nkl, 0, 2)
            )

            warp_group_idx = cute.arch.make_warp_uniform(tidx // self.num_threads_per_warp_group)
            mma_warp_group_thread_layout = cute.make_layout(self.num_mma_warp_groups, stride=self.num_threads_per_warp_group)
            thr_mma = tiled_mma.get_slice(mma_warp_group_thread_layout(warp_group_idx - self.num_dma_warp_groups))

            tCsA = thr_mma.partition_A(sA)
            tCsB = thr_mma.partition_B(sB)
            tCrA = tiled_mma.make_fragment_A(tCsA)
            tCrB = tiled_mma.make_fragment_B(tCsB)

            tCgC = thr_mma.partition_C(gC_mnl)
            acc_shape = tCgC.shape[:3]
            accumulators = cute.make_rmem_tensor(acc_shape, self.acc_dtype)

            k_tile_cnt = cute.size(gA_mkl, mode=[3])

            pipeline_init_wait(cluster_shape_mn=self.cluster_shape_mn)

            is_dma_warp_group = warp_group_idx < self.num_dma_warp_groups
            if is_dma_warp_group:
                cute.arch.setmaxregister_decrease(self.load_register_requirement)

            # ── DMA warp group ─────────────────────────────────────────────────
            if warp_idx == self.load_warp_id:
                tile_sched = utils_mod.StaticPersistentTileScheduler.create(
                    tile_sched_params, cute.arch.block_idx(), cute.arch.grid_dim()
                )
                work_tile = tile_sched.initial_work_tile_info()
                mainloop_producer_state = pipeline.make_pipeline_state(pipeline.PipelineUserType.Producer, self.ab_stage)

                while work_tile.is_valid_tile:
                    tile_coord_mnl = work_tile.tile_idx
                    tAgA_mkl = tAgA[(None, tile_coord_mnl[0], None, tile_coord_mnl[2])]
                    tBgB_nkl = tBgB[(None, tile_coord_mnl[1], None, tile_coord_mnl[2])]
                    mainloop_producer_state.reset_count()

                    for k_tile in range(k_tile_cnt):
                        mainloop_pipeline.producer_acquire(mainloop_producer_state)
                        tAgA_k = tAgA_mkl[(None, mainloop_producer_state.count)]
                        tAsA_pipe = tAsA[(None, mainloop_producer_state.index)]
                        tBgB_k = tBgB_nkl[(None, mainloop_producer_state.count)]
                        tBsB_pipe = tBsB[(None, mainloop_producer_state.index)]

                        cute.copy(
                            tma_atom_a,
                            tAgA_k,
                            tAsA_pipe,
                            tma_bar_ptr=mainloop_pipeline.producer_get_barrier(mainloop_producer_state),
                            mcast_mask=a_mcast_mask,
                        )
                        cute.copy(
                            tma_atom_b,
                            tBgB_k,
                            tBsB_pipe,
                            tma_bar_ptr=mainloop_pipeline.producer_get_barrier(mainloop_producer_state),
                            mcast_mask=b_mcast_mask,
                        )
                        mainloop_pipeline.producer_commit(mainloop_producer_state)
                        mainloop_producer_state.advance()

                    tile_sched.advance_to_next_work()
                    work_tile = tile_sched.get_current_work()

                mainloop_pipeline.producer_tail(mainloop_producer_state)

            # ── MMA warp group ─────────────────────────────────────────────────
            if not is_dma_warp_group:
                cute.arch.setmaxregister_increase(self.mma_register_requirement)
                tile_sched = utils_mod.StaticPersistentTileScheduler.create(
                    tile_sched_params, cute.arch.block_idx(), cute.arch.grid_dim()
                )
                work_tile = tile_sched.initial_work_tile_info()

                mainloop_consumer_read_state = pipeline.make_pipeline_state(pipeline.PipelineUserType.Consumer, self.ab_stage)
                mainloop_consumer_release_state = pipeline.make_pipeline_state(
                    pipeline.PipelineUserType.Consumer, self.ab_stage
                )

                num_k_blocks = cute.size(tCrA, mode=[2])

                import cutlass.utils.hopper_helpers as sm90_utils

                copy_atom_r2s = sm90_utils.sm90_get_smem_store_op(
                    self.c_layout, elem_ty_d=self.c_dtype, elem_ty_acc=self.acc_dtype
                )

                copy_atom_C = cute.make_copy_atom(
                    cute.nvgpu.warp.StMatrix8x8x16bOp(self.c_layout.is_m_major_c(), 4), self.c_dtype
                )
                tiled_copy_C_Atom = cute.make_tiled_copy_C_atom(copy_atom_C, tiled_mma)
                tiled_copy_r2s = cute.make_tiled_copy_S(copy_atom_r2s, tiled_copy_C_Atom)

                thr_copy_r2s = tiled_copy_r2s.get_slice(tidx - self.num_dma_warp_groups * self.num_threads_per_warp_group)
                tRS_sD = thr_copy_r2s.partition_D(sC)
                tRS_rAcc = tiled_copy_r2s.retile(accumulators)

                rD_shape = cute.shape(thr_copy_r2s.partition_S(sC))
                tRS_rD_layout = cute.make_layout(rD_shape[:3])
                tRS_rD = cute.make_rmem_tensor(tRS_rD_layout.shape, self.acc_dtype)
                tRS_rD_out = cute.make_rmem_tensor(tRS_rD_layout.shape, self.c_dtype)
                size_tRS_rD = cute.size(tRS_rD)

                k_pipe_mmas = 1
                prologue_mma_cnt = min(k_pipe_mmas, k_tile_cnt)

                tma_store_producer_group = pipeline.CooperativeGroup(pipeline.Agent.Thread, self.num_mma_threads)
                tma_store_pipeline = pipeline.PipelineTmaStore.create(
                    num_stages=self.epi_stage, producer_group=tma_store_producer_group
                )

                while work_tile.is_valid_tile:
                    tile_coord_mnl = work_tile.tile_idx
                    gC_mnl_slice = gC_mnl[(None, None, *tile_coord_mnl)]

                    mainloop_consumer_read_state.reset_count()
                    mainloop_consumer_release_state.reset_count()
                    accumulators.fill(0.0)
                    tiled_mma.set(cute.nvgpu.warpgroup.Field.ACCUMULATE, True)
                    cute.nvgpu.warpgroup.fence()

                    for k_tile in range(prologue_mma_cnt):
                        mainloop_pipeline.consumer_wait(mainloop_consumer_read_state)
                        for k_block_idx in cutlass.range_constexpr(num_k_blocks):
                            k_block_coord = (None, None, k_block_idx, mainloop_consumer_read_state.index)
                            cute.gemm(tiled_mma, accumulators, tCrA[k_block_coord], tCrB[k_block_coord], accumulators)
                        cute.nvgpu.warpgroup.commit_group()
                        mainloop_consumer_read_state.advance()

                    for k_tile in range(prologue_mma_cnt, k_tile_cnt):
                        mainloop_pipeline.consumer_wait(mainloop_consumer_read_state)
                        for k_block_idx in cutlass.range_constexpr(num_k_blocks):
                            k_block_coord = (None, None, k_block_idx, mainloop_consumer_read_state.index)
                            cute.gemm(tiled_mma, accumulators, tCrA[k_block_coord], tCrB[k_block_coord], accumulators)
                        cute.nvgpu.warpgroup.commit_group()
                        cute.nvgpu.warpgroup.wait_group(k_pipe_mmas)
                        mainloop_pipeline.consumer_release(mainloop_consumer_release_state)
                        mainloop_consumer_release_state.advance()
                        mainloop_consumer_read_state.advance()

                    cute.nvgpu.warpgroup.wait_group(0)
                    for k_tile in range(prologue_mma_cnt):
                        mainloop_pipeline.consumer_release(mainloop_consumer_release_state)
                        mainloop_consumer_release_state.advance()

                    # Epilogue
                    tCgC_for_tma_partition = cute.zipped_divide(gC_mnl_slice, self.epi_tile)
                    bSG_sD, bSG_gD = cute.nvgpu.cpasync.tma_partition(
                        tma_atom_c, 0, cute.make_layout(1), cute.group_modes(sC, 0, 2), tCgC_for_tma_partition
                    )
                    epi_tile_num = cute.size(tCgC_for_tma_partition, mode=[1])
                    epi_tile_shape = tCgC_for_tma_partition.shape[1]
                    epi_tile_layout = cute.make_layout(epi_tile_shape, stride=(epi_tile_shape[1], 1))
                    num_prev_epi_tiles = tile_sched.num_tiles_executed * epi_tile_num

                    for epi_idx in cutlass.range_constexpr(epi_tile_num):
                        for epi_v in cutlass.range_constexpr(size_tRS_rD):
                            tRS_rD[epi_v] = tRS_rAcc[epi_idx * size_tRS_rD + epi_v]

                        # ── Load FP32 accumulator tile ─────────────────────────
                        acc_vec = tRS_rD.load()

                        # ── FUSED EPILOGUE: apply in registers ─────────────────
                        acc_vec = self._apply_epilogue(acc_vec)

                        # ── Convert to output dtype and store ──────────────────
                        tRS_rD_out.store(acc_vec.to(self.c_dtype))

                        epi_buffer = (num_prev_epi_tiles + epi_idx) % cute.size(tRS_sD, mode=[3])
                        cute.copy(tiled_copy_r2s, tRS_rD_out, tRS_sD[(None, None, None, epi_buffer)])
                        cute.arch.fence_proxy("async.shared", space="cta")
                        self.epilog_sync_barrier.arrive_and_wait()

                        gmem_coord = epi_tile_layout.get_hier_coord(epi_idx)
                        if warp_idx == self.epi_store_warp_id:
                            cute.copy(tma_atom_c, bSG_sD[(None, epi_buffer)], bSG_gD[(None, gmem_coord)])
                            tma_store_pipeline.producer_commit()
                            tma_store_pipeline.producer_acquire()

                        self.epilog_sync_barrier.arrive_and_wait()

                    tile_sched.advance_to_next_work()
                    work_tile = tile_sched.get_current_work()

                tma_store_pipeline.producer_tail()


# ── Two-level fused GEMM cache ─────────────────────────────────────────────────
#
# Shape-polymorphism strategy
# ---------------------------
# ``cute.compile()`` with ``is_dynamic_layout=True`` produces a kernel binary
# that is polymorphic in the M dimension: a kernel compiled for template M=128
# can be called at runtime for any M (verified experimentally).  N and K are
# typically static (weight-matrix dimensions) while M = batch×seq_len varies.
#
# We therefore split the cache into two levels:
#
#   _COMPILED_CACHE  key: (N, K, epilogue_code, num_extras, reduce_n_by_2)
#                    value: _CompiledEntry (compiled_gemm)
#                    → populated once, reused for every new M
#
#   _BUFFER_CACHE    key: (M, N, K)
#                    value: _BufferEntry (a/b/c aligned device buffers + CuTe
#                           descriptors for the specific M)
#                    → populated once per unique M, much cheaper than recompile
#
# This ensures ``cute.compile()`` is called at most once per (N,K,...) config
# regardless of how many distinct M values appear at runtime.


@dataclass
class _CompiledEntry:
    """Compiled CuTe kernel — shape-polymorphic in the M dimension."""

    compiled_gemm: object  # result of cute.compile(...)
    max_active_clusters: int  # baked at compile time (HW-dependent constant)


@dataclass
class _BufferEntry:
    """Aligned device buffers and CuTe descriptors for a specific (M, N, K)."""

    a_cute: object
    a_ref: torch.Tensor  # (M, K, 1) — input A
    b_cute: object
    b_ref: torch.Tensor  # (N, K, 1) — input B (transposed)
    c_cute: object
    c_ref: torch.Tensor  # (M, N, 1) — output C


_COMPILED_CACHE: dict = {}  # (N, K, epi_code, num_extras, reduce_n) → _CompiledEntry | None
_BUFFER_CACHE: dict = {}  # (M, N, K) → _BufferEntry

_TILE_MN = (128, 256)
_CLUSTER_MN = (1, 1)
# Template M used for cute.compile(); the compiled kernel runs for any M.
_TEMPLATE_M = 128


def _compile_kernel(N: int, K: int, epilogue_fn, extra_cute_tensors: list) -> Optional[_CompiledEntry]:
    """Compile the fused GEMM kernel for fixed (N, K); polymorphic in M.

    Uses ``_TEMPLATE_M`` as a placeholder M during compilation — the resulting
    binary runs correctly for any M because ``is_dynamic_layout=True`` keeps
    M out of any ``Constexpr`` baked values.

    Returns None on any compilation failure.
    """
    if not _HAS_CUTLASS:
        return None
    if K % 8 != 0 or N % 8 != 0:
        return None

    M = _TEMPLATE_M
    l = 1
    a_dtype = cutlass.Float16
    b_dtype = cutlass.Float16
    c_dtype = cutlass.Float16
    acc_dtype = cutlass.Float32

    a_cpu = cutlass_torch.matrix(l, M, K, False, a_dtype)
    b_cpu = cutlass_torch.matrix(l, N, K, False, b_dtype)
    c_cpu = cutlass_torch.matrix(l, M, N, False, c_dtype)

    a_cute, _ = cutlass_torch.cute_tensor_like(a_cpu, a_dtype, is_dynamic_layout=True, assumed_align=16)
    b_cute, _ = cutlass_torch.cute_tensor_like(b_cpu, b_dtype, is_dynamic_layout=True, assumed_align=16)
    c_cute, _ = cutlass_torch.cute_tensor_like(c_cpu, c_dtype, is_dynamic_layout=True, assumed_align=16)

    gemm = HopperWgmmaGemmEpilogueFusedKernel(
        acc_dtype,
        _TILE_MN,
        _CLUSTER_MN,
        swizzle_size=1,
        raster_along_m=True,
        epilogue_fn=epilogue_fn,
        extra_cute_tensors=extra_cute_tensors,
    )

    hw = cutlass.utils.HardwareInfo()
    mac = hw.get_max_active_clusters(_CLUSTER_MN[0] * _CLUSTER_MN[1])
    cu_stream = cuda.CUstream(torch.cuda.current_stream().cuda_stream)

    try:
        compiled_gemm = cute.compile(gemm, a_cute, b_cute, c_cute, mac, cu_stream)
    except Exception:
        return None

    return _CompiledEntry(compiled_gemm=compiled_gemm, max_active_clusters=mac)


def _get_or_create_buffers(M: int, N: int, K: int) -> Optional[_BufferEntry]:
    """Return pre-allocated aligned CuTe buffers for the given (M, N, K).

    Allocates once per unique (M, N, K) and caches the result.  Allocation is
    much cheaper than ``cute.compile()`` but still non-trivial (GPU malloc +
    CuTe descriptor creation), so caching across calls with the same shape is
    important for training loops where M is fixed per microbatch.
    """
    buf_key = (M, N, K)
    if buf_key in _BUFFER_CACHE:
        return _BUFFER_CACHE[buf_key]

    if not _HAS_CUTLASS:
        return None

    l = 1
    a_dtype = cutlass.Float16
    b_dtype = cutlass.Float16
    c_dtype = cutlass.Float16

    a_cpu = cutlass_torch.matrix(l, M, K, False, a_dtype)
    b_cpu = cutlass_torch.matrix(l, N, K, False, b_dtype)
    c_cpu = cutlass_torch.matrix(l, M, N, False, c_dtype)

    try:
        a_cute, a_ref = cutlass_torch.cute_tensor_like(a_cpu, a_dtype, is_dynamic_layout=True, assumed_align=16)
        b_cute, b_ref = cutlass_torch.cute_tensor_like(b_cpu, b_dtype, is_dynamic_layout=True, assumed_align=16)
        c_cute, c_ref = cutlass_torch.cute_tensor_like(c_cpu, c_dtype, is_dynamic_layout=True, assumed_align=16)
    except Exception:
        _BUFFER_CACHE[buf_key] = None
        return None

    entry = _BufferEntry(a_cute=a_cute, a_ref=a_ref, b_cute=b_cute, b_ref=b_ref, c_cute=c_cute, c_ref=c_ref)
    _BUFFER_CACHE[buf_key] = entry
    return entry


def _compiled_cache_key(N, K, epilogue_code, num_extras, reduce_n_by_2):
    """Cache key for the compiled kernel — M-independent."""
    return (N, K, epilogue_code, num_extras, reduce_n_by_2)


# ── Public API ─────────────────────────────────────────────────────────────────


def matmul_cute_custom_epilogue(
    A: torch.Tensor, B: torch.Tensor, extras: list, epilogue_code: str, reduce_n_by_2: bool
) -> torch.Tensor:
    """Run GEMM + epilogue fully fused in the CuTe Hopper kernel.

    The epilogue is applied on the FP32 accumulator register file *before*
    type conversion and TMA store, saving one full read of the (M×N) result
    from global memory compared to a separate Triton epilogue pass.

    Shape-polymorphic caching
    -------------------------
    ``cute.compile()`` is called **at most once** per unique (N, K, epilogue)
    configuration regardless of how many distinct M values appear at runtime.
    For a typical transformer, N and K are static weight-matrix dimensions
    while M = batch×seq_len varies freely; this strategy ensures the expensive
    JIT compilation cost is paid only once per layer, not per step.

    At FX graph level, static dims satisfy ``type(d) is int`` on
    ``node.meta["val"].shape``; dynamic dims are ``torch.SymInt``.  This
    function exploits that structure automatically via the two-level cache.

    Falls back to ``matmul_custom_epilogue`` (Triton TMA-persistent) when:
      - Not running on Hopper (SM < 90), or
      - ``cutlass-dsl`` is not installed, or
      - The epilogue contains constructs not representable as CuTe register ops
        (e.g. SwiGLU ``tl.split``), or
      - The problem dimensions violate 16-byte alignment requirements.

    Parameters
    ----------
    A : torch.Tensor — (M, K) FP16 row-major
    B : torch.Tensor — (K, N) FP16 row-major
    extras : list[torch.Tensor]
        Additional bias / scale tensors referenced by the epilogue.
    epilogue_code : str
        Triton epilogue snippet from the fusion pass.
    reduce_n_by_2 : bool
        True for SwiGLU (output N = input N / 2).
    """
    M, K = A.shape
    _, N = B.shape

    if not _HAS_CUTLASS:
        return matmul_custom_epilogue(A, B, extras, epilogue_code, reduce_n_by_2)

    # ── Level-1: compiled kernel lookup (expensive; M-independent) ────────────
    compile_key = _compiled_cache_key(N, K, epilogue_code, len(extras), reduce_n_by_2)

    if compile_key not in _COMPILED_CACHE:
        epi_fn = _compile_epilogue_fn(epilogue_code, len(extras), reduce_n_by_2)

        if epi_fn is None:
            _COMPILED_CACHE[compile_key] = None
        else:
            extra_cute = []
            for t in extras:
                try:
                    from cutlass.cute.runtime import from_dlpack

                    extra_cute.append(from_dlpack(t, assumed_align=16))
                except Exception:
                    extra_cute = None
                    break

            if extra_cute is None:
                _COMPILED_CACHE[compile_key] = None
            else:
                compiled_entry = _compile_kernel(N, K, epi_fn, extra_cute)
                _COMPILED_CACHE[compile_key] = compiled_entry  # None on failure

    compiled_entry = _COMPILED_CACHE.get(compile_key)
    if compiled_entry is None:
        return matmul_custom_epilogue(A, B, extras, epilogue_code, reduce_n_by_2)

    # ── Level-2: buffer lookup (cheap; once per unique M) ─────────────────────
    buf = _get_or_create_buffers(M, N, K)
    if buf is None:
        return matmul_custom_epilogue(A, B, extras, epilogue_code, reduce_n_by_2)

    # ── Copy input data into aligned CuTe buffers ──────────────────────────────
    buf.a_ref.copy_(A.unsqueeze(2))
    buf.b_ref.copy_(B.T.contiguous().unsqueeze(2))

    # ── Run the fused CuTe kernel ──────────────────────────────────────────────
    cu_stream = cuda.CUstream(torch.cuda.current_stream().cuda_stream)
    compiled_entry.compiled_gemm(buf.a_cute, buf.b_cute, buf.c_cute, cu_stream)

    # ── Extract result ─────────────────────────────────────────────────────────
    N_out = N // 2 if reduce_n_by_2 else N
    elem_size = A.element_size()
    align_elems = 128 // elem_size
    N_stride = (N_out + align_elems - 1) // align_elems * align_elems
    D = torch.empty((M, N_stride), device=A.device, dtype=A.dtype)[:, :N_out]

    # c_ref layout is (M, N, 1); the kernel writes into it via TMA store
    D.copy_(buf.c_ref[:, :N_out, 0])
    return D
